### ISSUE TITLE
"Couldn't extract trace"

### ISSUE THREAD

**Issue by markerdmann** [Tenderly/tenderly-cli#3]
This is a very promising tool! We've been looking for something exactly like this.

I'm testing locally with the latest release (v0.2.6), but I'm not getting the expected stack trace that points to a line of code in the smart contract. For example, when I run `truffle exec` on one of the scripts I get this:

```
/usr/src/tenderly-cli/demo # truffle exec scripts/fail-multi-contract-1.js  --network proxy
Using network 'proxy'.

Successfully thrown error! Error: Invalid number of arguments to Solidity function
    at Object.InvalidNumberOfSolidityArgs (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:25:1)
    at SolidityFunction.validateArgs (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:74:1)
    at SolidityFunction.toPayload (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:90:1)
    at SolidityFunction.sendTransaction (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:163:1)
    at SolidityFunction.execute (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:256:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-contract/contract.js:204:1
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-contract/contract.js:155:1
```

And in the tenderly logs I see:

`Couldn't extract trace`

**Comment by BogdanHabic** [comment]
Hey Markus, thanks for checking out the tool!

From the output truffle gives you, it seems that you are passing an incorrect number of arguments to the function you are testing.

The reason why this isn't surfaced by our CLI it's because it never reaches your local node. If you check the error you get, you can see the code failed in the `validateArgs` function in `web3`. This means that either the ABI you used to call the contract isn't up to date or you are passing an incorrect number of arguments to your function.

I'm closing this issue, but feel free to reopen it if I'm mistaken. 😄

**Comment by markerdmann** [comment]
That's helpful, thanks @BogdanHabic! I tried the `fail-revert.js` script on an OSX machine today, and that gave me the expected stack trace that points to a line in the Solidity file.

IIRC I tried running `fail-revert.js` on a Linux machine last week but didn't get the stack trace. I'll double-check that when I'm back on a Linux machine next week and post relevant details if I run into an error.
