### ISSUE TITLE
Internal server error on init

### ISSUE THREAD

**Issue by choomz** [Tenderly/tenderly-cli#71]
Hello,

Just installed tenderly with brew, login is ok and when I try to init with the following command I get this return :

> tenderly init  --debug
Trying OpenZeppelin config path: networks.js
unable to fetch config
 Couldn't read OpenZeppelin config file
couldn't read new OpenzeppelinConfig config file
Trying buidler config path: buidler.config.js
unable to fetch config
 Couldn't read Buidler config file
couldn't read new Buidler config file
Trying hardhat config path: hardhat.config.js
unable to fetch config
 Couldn't read Hardhat config file
Trying hardhat ts config path: hardhat.config.ts
Making request
Got response with body
Couldn't detect provider directory structure. This can be caused by:

	• The directory is not set correctly. If this is the case, either check if you are in the right directory or pass an alternative directory by using the --project-dir flag.
	• Tenderly is having trouble reading the directory correctly. If you think this is the case, rerun this command with the --force flag.

or with `--force` flag

> tenderly init --force --debug
Making request
Got response with body
get projects call: internal_server_error
Internal Server Error

I got a standard hardhat project (only just src directory to run some node scripts).
![image](https://user-images.githubusercontent.com/1176482/151035416-c5a152d8-a7ec-4e12-a75b-9676a3366539.png)

I don't know how to get more verbose output in order to understand what is happening.

Can you please help ?
Thanks :)

**Comment by Riphal** [comment]
Hey, yesterday we have some problems with API but that is resolved, so tenderly init works now.
And I notice that tenderly init failed that is because you don't have a `deployments` directory inside your project.
You can generate that one using [hardhat-tenderly](https://github.com/Tenderly/hardhat-tenderly#readme.)
1.  To install hardhat-tenderly run.
```
    npm install --save-dev @tenderly/hardhat-tenderly
```
2. Add the following statement to your `hardhat.config.js`:
```
    require("@tenderly/hardhat-tenderly");
```
Or, if you are using typescript:
```
    import "@tenderly/hardhat-tenderly"
```

3. Then you need to call it from your scripts (using ethers to deploy a contract):
```
    const Greeter = await ethers.getContractFactory("Greeter");
    const greeter = await Greeter.deploy("Hello, Hardhat!");

    await greeter.deployed()

    await hre.tenderly.persistArtifacts({
        name: "Greeter",
        address: greeter.address,
    })
```
`persistArtifacts` accept variadic parameters:
```
    const contracts = [
    {
        name: "Greeter",
        address: "123"
    },
    {
        name: "Greeter2",
        address: "456"
    }]

    await hre.tenderly.persistArtifacts(...contracts)
```

4. Run: `npx hardhat compile` to compile contracts
5. Run: `npx hardhat node --network hardhat` to start a local node
6. Run: `npx hardhat run scripts/sample-script.js --network localhost` to run a script
7. And at the end now when `deployments` directory was built you can run `tenderly init`

**Comment by choomz** [comment]
Thanks :)

**Comment by tantely-npx** [comment]
> 

How do you push a contract/project on Tenderly dashboard with on a local network ?

**Comment by Riphal** [comment]
Currently, you can only export local transactions with [export local-transaction feature](https://docs.tenderly.co/debugger/exporting-a-local-transaction).

**Comment by tantely-npx** [comment]
> Currently, you can only export local transactions with [export local-transaction feature](https://docs.tenderly.co/debugger/exporting-a-local-transaction).

Ok, thanks @Riphal :)

**Comment by red-saint-nft** [comment]
I don't get a `deployment` directory after running all the commands

**Comment by Riphal** [comment]
Hey @red-saint-nft, there is a new version of the `hardhat-tenderly` plugin. [Here](https://github.com/Tenderly/hardhat-tenderly#installation) is readme how to set up a new environment.

**Comment by beruda** [comment]
@hung-native can you try with [this monkey fix](https://github.com/Tenderly/tenderly-cli/issues/108#issuecomment-1312219787)? It seems to have worked for other users.
